### ISSUE TITLE
Follow tailwindcss conventions

### ISSUE THREAD

**Issue by emargareten** [francoismassart/eslint-plugin-tailwindcss#109]
Just wondering if it's possible to follow tailwinds conventions?
https://tailwindcss.com/blog/automatic-class-sorting-with-prettier#how-classes-are-sorted

**Comment by francoismassart** [comment]
Yes, it is in my plans 😉

**Comment by francoismassart** [comment]
Here is a kitchensink of all classnames ordered by `prettier-plugin-tailwindcss`:

```js
[
  "custom",
  "group",
  "peer",
  "border-y-1",
  "border-t-3",
  "border-b-px",
  "prose",
  "prose-slate",
  "aspect-w-16",
  "aspect-h-9",
  "line-clamp-2",
  "custom2",
  "container",
  "sr-only",
  "pointer-events-auto",
  "visible",
  "sticky",
  "inset-0",
  "inset-y-1",
  "inset-x-2",
  "top-3",
  "right-4",
  "bottom-5",
  "left-6",
  "isolate",
  "z-auto",
  "order-1",
  "col-span-1",
  "col-start-2",
  "col-end-3",
  "row-span-1",
  "row-start-2",
  "row-end-3",
  "float-left",
  "clear-both",
  "m-0",
  "my-px",
  "mx-1.5",
  "mt-1",
  "mr-2",
  "mb-3",
  "ml-4",
  "box-border",
  "block",
  "aspect-auto",
  "h-0",
  "max-h-fit",
  "min-h-full",
  "w-0",
  "min-w-full",
  "max-w-fit",
  "flex-none",
  "flex-shrink",
  "shrink",
  "flex-grow",
  "grow",
  "basis-0",
  "table-fixed",
  "border-collapse",
  "origin-bottom-right",
  "translate-x-px",
  "translate-y-2",
  "rotate-90",
  "skew-y-0",
  "skew-x-2",
  "scale-0",
  "scale-y-50",
  "scale-x-75",
  "transform",
  "transform-gpu",
  "transform-none",
  "animate-spin",
  "cursor-text",
  "touch-auto",
  "select-none",
  "resize-none",
  "snap-x",
  "snap-mandatory",
  "snap-center",
  "snap-always",
  "scroll-m-0",
  "scroll-my-px",
  "scroll-mx-1.5",
  "scroll-mt-1",
  "scroll-mr-2",
  "scroll-mb-3",
  "scroll-ml-4",
  "scroll-p-0",
  "scroll-py-px",
  "scroll-px-1.5",
  "scroll-pt-1",
  "scroll-pr-2",
  "scroll-pb-3",
  "scroll-pl-4",
  "list-outside",
  "list-decimal",
  "appearance-none",
  "columns-1",
  "break-before-avoid-page",
  "break-inside-avoid-column",
  "break-after-auto",
  "auto-cols-min",
  "grid-flow-col",
  "auto-rows-min",
  "grid-cols-1",
  "grid-rows-1",
  "flex-col",
  "flex-wrap",
  "place-content-between",
  "place-items-stretch",
  "content-between",
  "items-baseline",
  "justify-start",
  "justify-items-center",
  "gap-0",
  "gap-x-1",
  "gap-y-2",
  "space-y-0",
  "space-x-1",
  "space-y-reverse",
  "space-y-reverse",
  "divide-x-2",
  "divide-y-4",
  "divide-y-reverse",
  "divide-x-reverse",
  "divide-dashed",
  "divide-black",
  "place-self-end",
  "self-baseline",
  "justify-self-stretch",
  "overflow-hidden",
  "overflow-x-auto",
  "overflow-y-scroll",
  "overscroll-auto",
  "overscroll-y-none",
  "overscroll-x-contain",
  "scroll-smooth",
  "overflow-ellipsis",
  "text-ellipsis",
  "whitespace-nowrap",
  "break-words",
  "rounded",
  "rounded-t-xl",
  "rounded-r-2xl",
  "rounded-b-sm",
  "rounded-l-none",
  "rounded-tl-xl",
  "rounded-tr-2xl",
  "rounded-br-sm",
  "rounded-bl-none",
  "border-0",
  "border-x-2",
  "border-r-4",
  "border-l",
  "border-solid",
  "border-black",
  "border-y-transparent",
  "border-x-slate-50",
  "border-t-white",
  "border-r-transparent",
  "border-b-inherit",
  "border-l-current",
  "bg-current",
  "bg-opacity-50",
  "bg-none",
  "from-current",
  "via-black",
  "to-orange-500",
  "decoration-clone",
  "box-decoration-clone",
  "bg-auto",
  "bg-fixed",
  "bg-clip-padding",
  "bg-bottom",
  "bg-no-repeat",
  "bg-origin-border",
  "fill-white",
  "stroke-white",
  "stroke-2",
  "object-contain",
  "object-bottom",
  "p-0",
  "py-px",
  "px-1.5",
  "pt-1",
  "pr-2",
  "pb-3",
  "pl-4",
  "text-left",
  "indent-px",
  "align-top",
  "font-sans",
  "text-lg",
  "font-semibold",
  "uppercase",
  "italic",
  "ordinal",
  "leading-4",
  "tracking-normal",
  "text-current",
  "underline",
  "decoration-black",
  "decoration-double",
  "decoration-from-font",
  "underline-offset-auto",
  "subpixel-antialiased",
  "caret-black",
  "accent-black",
  "opacity-50",
  "bg-blend-lighten",
  "mix-blend-darken",
  "shadow-lg",
  "shadow-white",
  "outline-dotted",
  "outline-0",
  "outline-offset-1",
  "outline-current",
  "ring-1",
  "ring-inset",
  "ring-white",
  "ring-opacity-50",
  "ring-offset-2",
  "ring-offset-current",
  "blur",
  "brightness-50",
  "contrast-100",
  "drop-shadow-xl",
  "grayscale",
  "hue-rotate-90",
  "invert",
  "saturate-100",
  "sepia",
  "filter",
  "backdrop-blur-lg",
  "backdrop-brightness-110",
  "backdrop-contrast-125",
  "backdrop-grayscale",
  "backdrop-hue-rotate-90",
  "backdrop-invert",
  "backdrop-opacity-30",
  "backdrop-saturate-100",
  "backdrop-sepia",
  "transition-all",
  "delay-150",
  "duration-1000",
  "ease-linear",
  "will-change-scroll",
  "content-none",
  "[--scroll-offset:56px]"
]
```

**Comment by xiCO2k** [comment]
That would be awesome, thanks for the package @francoismassart

**Comment by francoismassart** [comment]
I'm working on this when I can be guess who has been tested positive today ... 😞

**Comment by charkour** [comment]
Rest up!

**Comment by francoismassart** [comment]
👋  @emargareten , @xiCO2k , @jonnywilliamson , @SebasG22 , @SergeyRyzhkov , @dcmastenbroek , @shunkakinoki , @boompikachu, @charkour , @johnny353535


If you want to **test it out and provide feedback**, I just published **`eslint-plugin-tailwindcss@3.5.0-beta.0`** which adds a new option **`officialSorting`** for the `classnames-order` rule.

By default, it is **disabled** but set it to `true` and the ordering process will use the same logic as `prettier-plugin-tailwindcss`.
It is disabled on purpose to avoid getting a complete reordering of all classnames after upgrading the plugin.

Interested ?

1. Start your test/existing project with a clean slate (stash your current changes if necessary)
2. `npm i -D eslint-plugin-tailwindcss@3.5.0-beta.0`
3. In your `eslintrc` file, set `officialSorting` of `classnames-order` rule to `true`
4. Save and restart VSCode (just to be sure)
5. Test it out, most of the classnames should be reordered following the same order as `prettier-plugin-tailwindcss`

**Comment by jonnywilliamson** [comment]
Hmmm. Not sure what I'm doing wrong here. Using the beta above.

My `eslintrc.js`
```js
module.exports = {
    "plugins": ["tailwindcss"],
    extends: [
        // add more generic rulesets here, such as:
        // 'eslint:recommended',
        'plugin:vue/vue3-recommended',
        'plugin:tailwindcss/recommended'
    ],
    rules: {
        // override/add rules settings here, such as:
        // 'vue/no-unused-vars': 'error'
        "vue/multiline-html-element-content-newline": ["error", {
            "allowEmptyLines": true
        }],
        "vue/max-attributes-per-line": ["error", {
            "singleline": 3,
        }],
        "tailwindcss/classnames-order": [2, {
            "officialSorting": true
        }],
    }
}
```

And the Error I keep getting

```
CssSyntaxError: Error while loading rule 'tailwindcss/no-custom-classname': <css input>:1:1: Unexpected }
Occurred while linting /Users/jonathan/Code/ca.co/.eslintrc.js

[1m[31m>[39m[22m[90m 1 | [39m[33m}[39m
 [90m   | [39m[1m[31m^[39m[22m


CssSyntaxError: Error while loading rule 'tailwindcss/no-custom-classname': <css input>:1:1: Unexpected }
Occurred while linting /Users/jonathan/Code/ca.co/.eslintrc.js
    at Input.error (/Users/jonathan/Code/ca.co/node_modules/postcss/lib/input.js:148:16)
    at Parser.unexpectedClose (/Users/jonathan/Code/ca.co/node_modules/postcss/lib/parser.js:528:22)
    at Parser.end (/Users/jonathan/Code/ca.co/node_modules/postcss/lib/parser.js:363:12)
    at Parser.parse (/Users/jonathan/Code/ca.co/node_modules/postcss/lib/parser.js:43:16)
    at Function.parse (/Users/jonathan/Code/ca.co/node_modules/postcss/lib/parse.js:11:12)
    at generateClassnamesListSync (/Users/jonathan/Code/ca.co/node_modules/eslint-plugin-tailwindcss/lib/util/cssFiles.js:29:28)
    at Object.create (/Users/jonathan/Code/ca.co/node_modules/eslint-plugin-tailwindcss/lib/rules/no-custom-classname.js:90:33)
    at createRuleListeners (/Users/jonathan/Code/ca.co/node_modules/eslint/lib/linter/linter.js:915:21)
    at /Users/jonathan/Code/ca.co/node_modules/eslint/lib/linter/linter.js:1097:31
    at Array.forEach (<anonymous>)
Process finished with exit code -1

```


And my package.json

```js
    "devDependencies": {
        "@inertiajs/inertia": "^0.10.0",
        "@inertiajs/inertia-vue3": "^0.5.1",
        "@inertiajs/progress": "^0.2.6",
        "@tailwindcss/forms": "^0.4.0",
        "@tailwindcss/typography": "^0.5.0",
        "@vue/compiler-sfc": "^3.0.5",
        "axios": "^0.25",
        "eslint": "^8.8.0",
        "eslint-plugin-tailwindcss": "^3.5.0-beta.0",
        "eslint-plugin-vue": "^8.4.1",
```

**Comment by francoismassart** [comment]
@jonnywilliamson , it looks like the error you are getting is not related to this rule. For now, disable it by setting tailwindcss/no-custom-classname to « off ». 

You can open another ticket for your issue but it requires providing a demo repository demonstrating the issue.

**Comment by jonnywilliamson** [comment]
If I get a chance to make a new project and then set up the repo I'll do that. In the mean time I had to disable this plugin at the moment.

Here's showing what happens when I add the rule to turn off `tailwindcss/no-custom-classname`. It gets rid of the warning instantly.

![CleanShot 2022-02-09 at 09 19 04](https://user-images.githubusercontent.com/2513663/153165196-2d307401-6263-466d-826f-a999f17b78da.gif)


BUT....now it takes nearly 15-20 secs to format the page on save.

When I remove the tailwind plugin everything goes back to almost instant. 
![CleanShot 2022-02-09 at 09 31 03](https://user-images.githubusercontent.com/2513663/153167019-0ab3e32b-0f00-4f24-b251-49f5533a0e15.gif)


This is with a brand new Laravel 9 project installed last night and really only the eslint and vue plugin installed to.

**Comment by francoismassart** [comment]
Hi,
I think I'm done with COVID for now 🎉  and I'll spend more time on this issue after fixing other minor issues.

I'll warn you when I need more testing, thank you for the feedback.

**Comment by francoismassart** [comment]
I made some changes that are available in the beta channel `3.5.0-beta-1` and tested it on a real project with 242 tsx files.

For my perf tests, there is indeed a huge bump when you enable the `officialSorting` (`true`).

```
3.5.0-beta-1: lint + "officialSorting": false => 2s
3.5.0-beta-1: lint + "officialSorting": true => 9.5s
3.5.0-beta-1: lint + fix + "officialSorting": true => 15s
3.4.4: lint => 2s
```

For now,  if you need to use the "officialSorting", I would recommend to disable `tailwindcss/classnames-order` and use the official plugin.

If you cannot use prettier and you are patient, you can enable "officialSorting".

I'll publish the code and any contribution is as always appreciated.

More details:
```
3.5.0-beta-1: lint + "officialSorting": false => 2s
Rule                                   | Time (ms) | Relative
:--------------------------------------|----------:|--------:
tailwindcss/classnames-order           |  1964.303 |    35.3%
tailwindcss/enforces-shorthand         |  1875.691 |    33.7%
tailwindcss/no-custom-classname        |   241.807 |     4.3%
react/no-deprecated                    |   195.853 |     3.5%
tailwindcss/no-contradicting-classname |   192.120 |     3.4%
@typescript-eslint/no-unused-vars      |   168.323 |     3.0%
react/no-direct-mutation-state         |   119.898 |     2.2%
react/no-string-refs                   |    94.352 |     1.7%
simple-import-sort/imports             |    89.936 |     1.6%
react/require-render-return            |    81.218 |     1.5%

3.5.0-beta-1: lint + "officialSorting": true => 9.5s
Rule                                   | Time (ms) | Relative
:--------------------------------------|----------:|--------:
tailwindcss/classnames-order           |  9682.650 |    71.7%
tailwindcss/enforces-shorthand         |  1954.327 |    14.5%
tailwindcss/no-custom-classname        |   309.564 |     2.3%
tailwindcss/no-contradicting-classname |   226.955 |     1.7%
react/no-deprecated                    |   205.950 |     1.5%
@typescript-eslint/no-unused-vars      |   162.062 |     1.2%
react/no-direct-mutation-state         |   126.041 |     0.9%
react/no-string-refs                   |   103.083 |     0.8%
simple-import-sort/imports             |    91.255 |     0.7%
react/require-render-return            |    88.584 |     0.7%

3.5.0-beta-1: lint + fix + "officialSorting": true => 15s
Rule                                   | Time (ms) | Relative
:--------------------------------------|----------:|--------:
tailwindcss/classnames-order           | 15027.564 |    73.9%
tailwindcss/enforces-shorthand         |  3002.938 |    14.8%
tailwindcss/no-custom-classname        |   455.000 |     2.2%
tailwindcss/no-contradicting-classname |   306.564 |     1.5%
react/no-deprecated                    |   243.501 |     1.2%
@typescript-eslint/no-unused-vars      |   171.053 |     0.8%
react/no-direct-mutation-state         |   148.076 |     0.7%
react/no-string-refs                   |   119.265 |     0.6%
react/require-render-return            |   104.248 |     0.5%
simple-import-sort/imports             |   100.538 |     0.5%

3.4.4: lint => 2s
Rule                                   | Time (ms) | Relative
:--------------------------------------|----------:|--------:
tailwindcss/classnames-order           |  2220.710 |    36.2%
tailwindcss/enforces-shorthand         |  1997.192 |    32.6%
tailwindcss/no-custom-classname        |   358.226 |     5.8%
tailwindcss/no-contradicting-classname |   219.180 |     3.6%
react/no-deprecated                    |   199.633 |     3.3%
@typescript-eslint/no-unused-vars      |   165.674 |     2.7%
react/no-direct-mutation-state         |   131.348 |     2.1%
react/no-string-refs                   |   100.552 |     1.6%
react/require-render-return            |    90.354 |     1.5%
simple-import-sort/imports             |    90.012 |     1.5%
```

**Comment by francoismassart** [comment]
I did attempt to "cache" the `order` value generated by calls to [`generateRules`](https://github.com/francoismassart/eslint-plugin-tailwindcss/blob/fix/official-sorting-and-spaces-zipper/lib/util/prettier/order.js#L13) but perfs are even worse...

**Comment by francoismassart** [comment]
👋  @emargareten , @xiCO2k , @jonnywilliamson , @SebasG22 , @SergeyRyzhkov , @dcmastenbroek , @shunkakinoki , @boompikachu, @charkour , @johnny353535

Please take some time to test `3.5.0-beta.2` and provide feedback:

`npm i -D eslint-plugin-tailwindcss@3.5.0-beta.2`

🙏 Thanks

**Comment by akornmeier** [comment]
@francoismassart - I wanted to report feedback of an example inconsistency with the eslint plugin and the prettier "officialSorting" setting. I am using the latest `eslint-plugin-tailwindcss@3.5.0-beta.2` and the following conflicting sorts are taking place: 

**Prettier Sort**: "text-large flex h-9 w-9 items-center justify-center rounded-full border-4 border-solid border-blue-100 bg-deque-blue text-white"
**eslint sort**: "text-large bg-deque-blue flex h-9 w-9 items-center justify-center rounded-full border-4 border-solid border-blue-100 text-white"

The class "bg-deque-blue" is an extended theme color. Hopefully this helps.

**Comment by francoismassart** [comment]
@akornmeier please share the tailwind config used in your previous comment...

If I paste your classnames as is (with the default config) in the playground: https://play.tailwindcss.com/R6HyPRucty
I have 2 custom (unrecognized) classnames (no tooltip with generated css on hover):

- `text-large`
- `bg-deque-blue`

If the eslint-plugin-tailwindcss did not get the tailwind config file, it will have an impact on the order as well...

**Comment by francoismassart** [comment]
Here is a playground link with an edited config which generates the 2 missing classnames

https://play.tailwindcss.com/8C5UoD7oA3

**Comment by francoismassart** [comment]
I just tested your example using `prettier-plugin-tailwindcss` +  the config as in https://play.tailwindcss.com/8C5UoD7oA3

Here is the sorted classList I get with prettier:
`flex h-9 w-9 items-center justify-center rounded-full border-4 border-solid border-blue-100 bg-deque-blue text-large text-white`
Which is matching eslint.

**Comment by francoismassart** [comment]
👋 @emargareten , @xiCO2k , @jonnywilliamson , @SebasG22 , @SergeyRyzhkov , @dcmastenbroek , @shunkakinoki , @boompikachu, @charkour , @johnny353535
latest version (`3.5.0`) support the new option `officialSorting`

**Comment by xiCO2k** [comment]
Works great thanks @francoismassart
