### ISSUE TITLE
[BUG] Unexpected token in classnames-order.js

### ISSUE THREAD

**Issue by tgrosinger** [francoismassart/eslint-plugin-tailwindcss#184]
**Describe the bug**

Running `npx eslint .` after adding this plugin results in a SyntaxError

```
$ npx eslint templates/

Oops! Something went wrong! :(

ESLint: 8.28.0

/workspaces/tonyslist/node_modules/eslint-plugin-tailwindcss/lib/rules/classnames-order.js:174
        const w = whitespaces[i] ?? '';
                                  ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/workspaces/tonyslist/node_modules/eslint-plugin-tailwindcss/lib/index.js:15:25)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
npm ERR! code 2
npm ERR! path /workspaces/tonyslist
npm ERR! command failed
npm ERR! command sh -c eslint "templates/"
```

**Environment:**
 - OS: [e.g. macOS, windows 10]
   - Ubuntu in WSL2, using a debian:bullseye devcontainer
 - Softwares + version used:
   - VSCode 1.73.1
   - npm 7.5.2
   - node 12.22.12
   - eslint 8.28.0

**eslint config file or live demo**

`package.json`:

```
{
  "scripts": {
    "format": "prettier --write templates",
    "eslint": "eslint templates"
  },
  "devDependencies": {
    "@tailwindcss/aspect-ratio": "^0.4.0",
    "@tailwindcss/forms": "^0.5.2",
    "eslint": "^8.28.0",
    "eslint-plugin-tailwindcss": "^3.7.0",
    "prettier": "^2.8.0",
    "prettier-plugin-go-template": "^0.0.13",
    "prettier-plugin-tailwindcss": "^0.2.0",
    "tailwindcss": "^3.1.8"
  }
}
```

`.eslintrc`:

```
{
  "extends": [
    "plugin:tailwindcss/recommended"
  ],
  "plugins": ["tailwindcss"],
  "ignorePatterns": ["templates/emails/*"]
}
```

**Comment by florianmAmrax** [comment]
Hey guys! I fought through this. It does not seem to be an issue with tailwindcss.
The thing that solved it for me was to update my node version. Apperently node 12 does not work with this syntax.

Hope this helps!
Have a nice day :)

**Comment by francoismassart** [comment]
Using node 16 and up fixes the issue
