### ISSUE TITLE
[BUG] Node must be provided when reporting error if location is not provided at assertValidNodeInfo

### ISSUE THREAD

**Issue by milaabl** [francoismassart/eslint-plugin-tailwindcss#279]
> AssertionError [ERR_ASSERTION]: Node must be provided when reporting error if location is not provided  
>     at assertValidNodeInfo (C:\Users\milaa\Desktop\Documents\[hidden for privacy]\node_modules\eslint\lib\linter\report-translator.js:83:9)

The error happens unexpectedly running `eslint --fix ./src` script.

My **.eslintrc.json** file is:

```
{
  "extends": [
    "eslint:recommended",
    "plugin:react/recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:tailwindcss/recommended"
  ],
  "parser": "@typescript-eslint/parser",
  "env": {
    "browser": true,
    "es2021": true
  },
  "overrides": [],
  "parserOptions": {
    "ecmaVersion": "latest",
    "sourceType": "module"
  },
  "plugins": [
    "react",
    "@typescript-eslint",
    "react-hooks",
    "redux-saga",
    "prettier",
    "simple-import-sort"
  ],
  "rules": {
    "react-hooks/rules-of-hooks": "error",
    "react-hooks/exhaustive-deps": "warn",
    "redux-saga/yield-effects": "warn",
    "redux-saga/no-unhandled-errors": "off",
    "jsx-a11y/click-events-have-key-events": "off",
    "react/react-in-jsx-scope": "off"
  }
}

```

**Scripts are:**

```
"scripts": {
    "dev": "vite --port 3030",
    "start": "vite --port 3030",
    "build": "tsc && vite build",
    "preview": "vite preview",
    "lint": "eslint --fix ./src && prettier --write --single-quote ./src",
    "format": "prettier . --write",
    "prepare": "husky install"
  },
```

The problem started occuring running `npm run lint`.

    
 **My dev dependencies are:**
 
```
 "devDependencies": {
    "@commitlint/cli": "^17.5.0",
    "@commitlint/config-conventional": "^17.4.4",
    "@types/react": "^18.2.22",
    "@types/react-dom": "^18.2.7",
    "@typescript-eslint/eslint-plugin": "^5.56.0",
    "@typescript-eslint/parser": "^5.56.0",
    "@vitejs/plugin-react": "^3.1.0",
    "eslint": "^8.36.0",
    "eslint-config-prettier": "^8.8.0",
    "eslint-config-standard-with-typescript": "^34.0.1",
    "eslint-import-resolver-typescript": "^3.5.3",
    "eslint-plugin-import": "^2.27.5",
    "eslint-plugin-n": "^15.6.1",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-promise": "^6.1.1",
    "eslint-plugin-react": "^7.32.2",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-redux-saga": "^1.3.2",
    "eslint-plugin-simple-import-sort": "^10.0.0",
    "eslint-plugin-tailwindcss": "^3.13.0",
    "husky": "^8.0.3",
    "lint-staged": "^13.2.0",
    "prettier": "^3.0.3",
    "prettier-plugin-organize-imports": "^3.2.3",
    "prettier-plugin-tailwindcss": "^0.5.4",
    "tailwind-scrollbar": "^3.0.5",
    "typescript": "^5.2.2",
    "vite": "^4.1.4"
  },
```

The error log:

```
at C:\Users\milaa\Desktop\Documents\[trimmed for privacy]\node_modules\eslint-plugin-tailwindcss\lib\rules\no-contradicting-classname.js:146:21
    at Array.forEach (<anonymous>)
    at C:\Users\milaa\Desktop\Documents\[trimmed for privacy]\node_modules\eslint-plugin-tailwindcss\lib\rules\no-contradicting-classname.js:143:29
    at Array.forEach (<anonymous>)
    at parseForContradictingClassNames (C:\Users\milaa\Desktop\Documents\[trimmed for privacy]\node_modules\eslint-plugin-tailwindcss\lib\rules\no-contradicting-classname.js:107:20)
    at parseNodeRecursive (C:\Users\milaa\Desktop\Documents\[trimmed for privacy]\node_modules\eslint-plugin-tailwindcss\lib\util\ast.js:330:5)
    at parseNodeRecursive (C:\Users\milaa\Desktop\Documents\[trimmed for privacy]\node_modules\eslint-plugin-tailwindcss\lib\util\ast.js:277:9)
```

**Comment by milaabl** [comment]
@francoismassart, thank you for the superb library, that's a life saver for large-scale TailwindCSS projects. However, I noticed an error ocurring today in my project.

Could you please help me figure out the issue?

**Comment by milaabl** [comment]
What might be causing that error?

**Comment by francoismassart** [comment]
Hi @milaabl,
could you take some time to put together a demo project only meant to demonstrate the issue so that I can inspect it on my own ? Thanks

**Comment by neviaumi** [comment]
I got same error by below config 

```js
const {default: tailwindCssConfig} = await import('@busybox/tailwindcss-config');
import { withColors } from '@busybox/tailwindcss-config/themes/colors';
import { withSpacing } from '@busybox/tailwindcss-config/themes/spacing';


/** @type {import('tailwindcss').Config} */
const config = {
  content: [
    './cypress/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
    './.storybook/**/*.{js,cjs}',
  ],
  presets: [withSpacing(withColors(tailwindCssConfig))],
  theme: {
    extend: {
      keyframes: {
        hide: {
          from: { transform: 'scale(1)' },
          to: { transform: 'scale(0)' },
        },
        show: {
          from: { transform: 'scale(0)' },
          to: { transform: 'scale(1)' },
        },
      },
    },
  },
};

export default config;
```

Eslint config
```js
import busyboxEslintConfig, { globals } from '@busybox/eslint-config';
import eslintPluginImport from '@busybox/eslint-config/plugins/eslint-plugin-import';

export default [
  {
    languageOptions: {
      globals: {
        ...globals.node,
      },
    },
  },
  {
    ignores: ['package-lock.json', 'storybook-static/', 'dist/'],
  },
  ...busyboxEslintConfig,
  {
    files: ['**/*.cy.tsx'],
    rules: {
      'react-refresh/only-export-components': 'off',
    },
  },
  {
    files: ['**/*.tsx'],
    plugins: {
      import: eslintPluginImport,
    },
    rules: {
      'import/no-default-export': ['error'],
      'import/prefer-default-export': 'off',
    },
  },
  {
    files: [
      '**/*.stories.tsx',
      './tailwind.config.mjs',
      './vite.config.ts',
      './.storybook/main.ts',
      './cypress.config.ts',
      './.storybook/preview.ts',
    ],
    plugins: {
      import: eslintPluginImport,
    },
    rules: {
      'import/no-default-export': 'off',
    },
  },
  {
    files: ['**/fixtures/*.ts'],
    rules: {
      'max-lines': 'off',
    },
  },
];
```

I am using Flag config in my project.

**Comment by neviaumi** [comment]
Also, if i do `node ./tailwind.config.mjs` it would be fine. (exit code with 0)

**Comment by milaabl** [comment]
> Also, if i do `node ./tailwind.config.mjs` it would be fine. (exit code with 0)

Does it actually format anything if you work it around with `node ./tailwind.config.mjs`?

**Comment by neviaumi** [comment]
@milaabl i don't get what is your question. 

But indeed i solved my problem already by do following: 

1. Remove `async import` on tailwindcss config
```js
import tailwindCssConfig from '@busybox/tailwindcss-config';
import { withColors } from '@busybox/tailwindcss-config/themes/colors';
import { withSpacing } from '@busybox/tailwindcss-config/themes/spacing';

/** @type {import('tailwindcss').Config} */
const config = {
  content: [
    './cypress/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
    './.storybook/**/*.{js,cjs}',
  ],
  presets: [withSpacing(withColors(tailwindCssConfig))],
  theme: {
    extend: {
      keyframes: {
        hide: {
          from: { transform: 'scale(1)' },
          to: { transform: 'scale(0)' },
        },
        show: {
          from: { transform: 'scale(0)' },
          to: { transform: 'scale(1)' },
        },
      },
    },
  },
};

export default config;
```

2. In `@busybox/tailwindcss-config` , i added `require` in export field  on [my tailwindcss package.json](https://github.com/neviaumi/busybox/blob/cdc03559066a74f7b4448969e38675b983bda01b/packages/tailwindcss-config/package.json#L16)
```json
{
 ".": {
      "import": "./tailwind.config.js",
      "require": "./tailwind.config.cjs"
    },
    "./tailwind.css": "./tailwind.css",
    "./themes/colors": {
      "import": "./themes/with-colors.js",
      "require": "./themes/with-colors.cjs"
    },
    "./themes/spacing": {
      "import": "./themes/with-spacing.js",
      "require": "./themes/with-spacing.cjs"
    }
}
```


I think the issue root cause is come from `jiti` [package used by tailwindcss to loadConfig](https://github.com/tailwindlabs/tailwindcss/blob/f945fc82f28634eccac25a473895e96fd815de84/src/lib/load-config.ts#L29) rather than plugin here :) 

Probably i should open issue on tailwind-css repo rather than here if i want get it spotlighted

**Comment by milaabl** [comment]
@neviaumi, oh it's great to know!! Thanks! ;)
