### ISSUE TITLE
[Feature request] Support Tailwind 4

### ISSUE THREAD

**Issue by aslakhellesoy** [francoismassart/eslint-plugin-tailwindcss#325]
**Is your feature request related to a problem? Please describe.**

TailwindCSS 4 is in alpha and will be released soon. Currently I cannot use this module with Tailwind 4 because `package.json` specifies `^3.4.0`.

**Describe the solution you'd like**

A new release that supports both `^3` and `^4`.

**Describe alternatives you've considered**

I tried updating `tailwindcss` to `4.0.0-alpha.9` in `peerDependencies` and `devDependencies`, but `npm install` failed because of other dependencies:

* `@tailwindcss/aspect-ratio`
* `@tailwindcss/forms`
* `@tailwindcss/line-clamp`
* `@tailwindcss/typography`

These all depend on `tailwindcss` version `^3`.

I'm not sure when/if those plugins will be updated for Tailwind 4.

**Additional context**

Will this need some help from the maintainers of the 4 modules above?

**Comment by francoismassart** [comment]
Making the eslint-plugin-tailwindcss compatible with Tailwind CSS v4 won't be easy and it'll definitively take a lot of time. One of the main challenge will be to workaround the possible the absence of tailwind.config.js file.

Parsing of existing CSS file (containing the CSS vars) is also very slow compared to native config...

I'll work on it but keep in mind this project is free and I can only work on it on my free time 😉

**Comment by xiBread** [comment]
Note that v4 is not planned to be stable until summer ([source](https://twitter.com/adamwathan/status/1763589839851516362) so this shouldn't be a huge priority.

**Comment by virtuallyunknown** [comment]
@francoismassart in their announcement post about v4, they mention that configuration would still be available with a `tailwind.config.js` file, and it's something on their roadmap.

> Support for JavaScript configuration files — reintroducing compatibility with the classic `tailwind.config.js` file to make migrating to v4 easy.

https://tailwindcss.com/blog/tailwindcss-v4-alpha#roadmap-to-v4-0

So in case parsing CSS proves to be too difficult, inefficient or time-consuming, would you be open to the idea of having such file mandatory in order to use `eslint-plugin-tailwindcss`?

To be totally honest here, I am not completely sold on the idea of defining all colors and other variables in a CSS file to begin with, so who knows, I can see people that will prefer to stick with the good old config file, especially if config-less Tailwind breaks other tools such as this one.

The only worrying part here is that they mention they are doing this to make v4 migrations easy, which may or may not imply they plan to get rid of it altogether in some later version, but I could be wrong.

**Comment by francoismassart** [comment]
I started reading the `next` branch of Tailwind CSS's codebase and I'll work on it soon on my free time, I've a full time job to comply to 😉

**Comment by francoismassart** [comment]
Quick update on `v4` of `eslint-plugin-tailwindcss`:

- It'll use the following stack:
  - **Turborepo** with:
    - `eslint-plugin-tailwindcss` as a `package`
    - several playgrounds as `apps` (React.js, Vue, etc.) for easier live testing
  - **TypeScript**
  - **Vitest**
  - `@typescript-eslint`
  - `eslint-doc-generator`
- It'll only support Tailwind CSS v4, we'll drop support for v3
- All rules will be rewritten and the strategy is to be based as much as possible on Tailwind CSS exposed methods:
  - better performances
  - stable results
  - custom logic will be added only when required
- I don't have a lot of time to work on it as it is a side project, you can contribute:
  - Become a [sponsor on GitHub](https://github.com/sponsors/francoismassart) or via [thanks.dev](https://thanks.dev/r/gh/francoismassart)
  - Make pull requests or provide exhaustive issues or feedbacks
  - Share the project on social medias
  - **Lastly, the project is used by almost 40K projects, yet it has only 1.3K stars.**
    _I hope reaching **at least 4K stars might offer me the free usage of Copilot** which I do not have._

**Comment by Frikadellios** [comment]
Hello 👋, 

Find some trouble with tailwind CLI, when use last alpha version with NPM.

`audit fix --force`

Installed latest tailwind 3 CLI.

Use it with astro js framework and node(18-20), maybe this is a reason, I don't know.

And I don't see this bug, If I am using Bun with bunx --bun command... 

But in both ways, See problem with output.css file in vertical alight ... I don't now why, can it be biome if I migrated from prettier with tailwind css plugin...

Why?

**Comment by romansp** [comment]
[v4 beta is out](https://tailwindcss.com/blog/tailwindcss-v4-beta)

Seems like `resolveConfig` is [no longer exported](https://tailwindcss.com/docs/v4-beta#referencing-theme-values-in-js) causing eslint to crash during loading: 

```
[Error - 4:03:00 PM] Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './resolveConfig' is not defined by "exports" in [redacted]/node_modules/tailwindcss/package.json
    at exportsNotFound (node:internal/modules/esm/resolve:304:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:651:9)
    at resolveExports (node:internal/modules/cjs/loader:592:36)
    at Module._findPath (node:internal/modules/cjs/loader:669:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1131:27)
    at Module._load (node:internal/modules/cjs/loader:986:27)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> ([redacted]/node_modules/eslint-plugin-tailwindcss/lib/util/customConfig.js:5:23)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
```

**Comment by benweier** [comment]
Really keen to see Tailwind v4 support <3

**Comment by Bricklou** [comment]
It's time! It just dropped a few hours ago! 😄

https://tailwindcss.com/blog/tailwindcss-v4

**Comment by ImBIOS** [comment]
I think this repo need some financial support

**Comment by mohammadgarmroodi** [comment]
I have this problem even in tailwind version 4 !

**Comment by mohammadgarmroodi** [comment]
> [v4 beta is out](https://tailwindcss.com/blog/tailwindcss-v4-beta)
> 
> Seems like `resolveConfig` is [no longer exported](https://tailwindcss.com/docs/v4-beta#referencing-theme-values-in-js) causing eslint to crash during loading:
> 
> ```
> [Error - 4:03:00 PM] Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './resolveConfig' is not defined by "exports" in [redacted]/node_modules/tailwindcss/package.json
>     at exportsNotFound (node:internal/modules/esm/resolve:304:10)
>     at packageExportsResolve (node:internal/modules/esm/resolve:651:9)
>     at resolveExports (node:internal/modules/cjs/loader:592:36)
>     at Module._findPath (node:internal/modules/cjs/loader:669:31)
>     at Module._resolveFilename (node:internal/modules/cjs/loader:1131:27)
>     at Module._load (node:internal/modules/cjs/loader:986:27)
>     at Module.require (node:internal/modules/cjs/loader:1233:19)
>     at require (node:internal/modules/helpers:179:18)
>     at Object.<anonymous> ([redacted]/node_modules/eslint-plugin-tailwindcss/lib/util/customConfig.js:5:23)
>     at Module._compile (node:internal/modules/cjs/loader:1358:14)
> ```

I have this problem even in tailwind version 4 !

**Comment by FDiskas** [comment]
Maybe it is a good idea to check the source of official tailwind vscode plugin - there may be some useful functions or solutions

https://github.com/tailwindlabs/tailwindcss-intellisense/blob/c9fb9bc04c0158c6e47e0c25a6600a21f335049a/packages/vscode-tailwindcss/src/extension.ts#L91-L105

**Comment by SilentImp** [comment]
Having same issue. 
Did try different versions of tailwindcss and eslint-plugin-tailwindcss, but nothing seems to work, keeping in mind ESLint v9, which limit lowest possible eslint-plugin-tailwindcss version.

```
> eslintint

Oops! Something went wrong! :(

ESLint: 9.18.0

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './resolveConfig' is not defined by "exports" in ...\node_modules\.pnpm\eslint-plugin-tailwindcss@3.18.0_tailwindcss@4.0.0\node_modules\tailwindcss\package.json

```

Any solution for this?

**Comment by nathan-de-pachtere** [comment]
Also have this issue in a monorepo powered by Moonrepo. 

https://github.com/tailwindlabs/tailwindcss/discussions/15945

**Comment by FDiskas** [comment]
I do believe that tailwind v4 has braking changes and eslint plugin for that will not happen soon.

**Comment by Kamahl19** [comment]
It needs to be rewritten from scratch

**Comment by cloud-walker** [comment]
but it would not working as an eslint plugin right? Or with eslint you can target also CSS files (I'm ignorant on the topic, but my current mental model is that eslint is for js stuff, not for CSS)

**Comment by incutonez** [comment]
> And to read the configuration, Tailwind might have some helpers to do that

The [prettier plugin](https://github.com/tailwindlabs/prettier-plugin-tailwindcss) might have some clues about how they handle this too.

**Comment by imddc** [comment]
When can it be adapted to v4? Looking forward to it.

**Comment by ShayanTheNerd** [comment]
> sorting class names (`className="a c d b"` -> `className="a b c d"`) doesn't require the config, I assume.

Actually, it does and that's because of the same reason we set the `tailwindStylesheet` option for [prettier-plugin-tailwindcss](https://github.com/tailwindlabs/prettier-plugin-tailwindcss#specifying-your-tailwind-stylesheet-path): the formatter needs to know about the customized colors, breakpoints, etc. so that, for example, it can sort `class="laptop:p-5 p-3"` to `class="p-3 laptop:p-5"`.

**Comment by item4** [comment]
please pin this issue top of issue tracker

**Comment by Pkcarreno** [comment]
I came across this post, I think it might be useful: [https://eslint.org/blog/2025/02/eslint-css-support/](https://eslint.org/blog/2025/02/eslint-css-support/)

**Comment by ariesclark** [comment]
> I think this repo need some financial support
@ImBIOS 

It needs a new maintainer, the current one has closed issues for performance instead of fixing them.
https://github.com/francoismassart/eslint-plugin-tailwindcss/issues/276#issuecomment-2150758111

**Comment by will-stone** [comment]
@ariesclark Have some respect mate! Francois (and contributors) have done a great job so far. They closed that issue because a PR was merged that was supposed to address it. If there's an issue, post-PR, open a new one; you were asked to provide more information and you didn't. Also @francoismassart has stated several times that this is a side project that they need to fit around work and life.

The changes TW made in v4 were dramatic, supporting that I can imagine is going to take some time. Whilst you wait, I'd suggest that you just stop using this plugin and lean more on the official Prettier and VSCode plugins (that's what I'm doing).

Why did I feel the need to reply? Because there's a lot of us (most likely) subscribed to this issue that just got pinged when you replied calling for new management, which is not polite in the FOSS world.

**Comment by ariesclark** [comment]
@will-stone It was an ill-thought-out reply, my apologizes.

**Comment by ImBIOS** [comment]
> @ariesclark Have some respect mate! Francois (and contributors) have done a great job so far. They closed that issue because a PR was merged that was supposed to address it. If there's an issue, post-PR, open a new one; you were asked to provide more information and you didn't. Also @francoismassart has stated several times that this is a side project that they need to fit around work and life.
> 
> The changes TW made in v4 were dramatic, supporting that I can imagine is going to take some time. Whilst you wait, I'd suggest that you just stop using this plugin and lean more on the official Prettier and VSCode plugins (that's what I'm doing).
> 
> Why did I feel the need to reply? Because there's a lot of us (most likely) subscribed to this issue that just got pinged when you replied calling for new management, which is not polite in the FOSS world.

That's nice explanation. That's why I tell everyone who need this support ASAP to open GitHub Sponsor and give financial support to the maintainers. If not, just wait patiently until maintainer's free times comes in.

**Comment by will-stone** [comment]
@ImBIOS remember though that providing sponsorship is for saying thank you for a job well done, and not for features you want right now; it should never be "if you add this one thing then I'd be willing to sponsor you".

I read an article once that summed this up nicely but I can't find it, but it essentially boils down to the fact you could never (unless you're mega rich) provide enough financial support for someone to quit their job and maintain this project for you, so the answer to these things is _always_ "wait patiently until maintainer's free times comes in" ... but an extra bit of pocket money here or there certainly can't hurt 🙂

**Comment by virtuallyunknown** [comment]
I agree with all the previous comments here obviously, but I also think communication here could be better. This is a relatively large project with almost 2k stars, so a lot of developers depend on it. In that line of thoughts, I think it would be great if the author provides an update, whatever that update might be. Not because he owes anything to anyone, but because it's a nice thing to do.

As far as I can tell, the latest response is from June 2024, someone feel free to correct me if I'm wrong.

**Comment by PatrykKuniczak** [comment]
v4 support will occur before v5 will be released? 🤔

**Comment by hyoban** [comment]
I am currently trying to support Tailwind v4 in my forked repository (it also supports v3). You are welcome to try and give feedback.

- https://github.com/hyoban/eslint-plugin-tailwindcss/pull/3

**Comment by Ryan-Zayne** [comment]
> I am currently trying to support Tailwind v4 in my forked repository (it also supports v3). You are welcome to try and give feedback.
> 
> * [refactor!: move to tailwind api utils, tailwind v4 support hyoban/eslint-plugin-tailwindcss#3](https://github.com/hyoban/eslint-plugin-tailwindcss/pull/3)

Finally! I'll definitely switch to once it's ready!
Thank you

**Comment by vedmant** [comment]
Tried to upgrade to Tailwind 4 and this is still the issue, downgraded to Tailwind 3 for now.

**Comment by TanjimulSabbir** [comment]
I think this command will resolve 'eslint-plugin-tailwindcss' with Tailwind v4. The command:-

`npm install eslint-plugin-tailwindcss@beta --save-dev --legacy-peer-deps`

**Comment by sarimarton-ofsz** [comment]
Workaround:

- generate a legacy v3 tailwind.v3.config.cjs with AI
- set the config in the plugin settings, so you can avoid the config lookup:

const require = createRequire(import.meta.url)
const tailwindV3Config = require("./tailwind.v3.config.cjs")
...
.settings.tailwindcss.config = tailwindV3Config

**Comment by lachieh** [comment]
The maintainer may have had a life change that means they are unable to support this project anymore since there hasn't been any commits here for 3 months. Unfortunately, it happens.

I'd suggest migrating to https://github.com/schoero/eslint-plugin-better-tailwindcss which has more rules and is more actively maintained (and even has planned support with oxlint 🦀).

**Comment by robbieaverill** [comment]
Just want to follow up on the previous comment and point out that this repo has a `^4.0.0-beta` release line which has Tailwind v4 support in it.

**Comment by stevenvachon** [comment]
7 months in beta; any plans to release a final?

**Comment by dilincoln** [comment]
> 7 months in beta; any plans to release a final?

Just migrate to Biome. That's what I did.

**Comment by dimitriBouteille** [comment]
You can use this plugin : https://github.com/schoero/eslint-plugin-better-tailwindcss

**Comment by peterwangsc** [comment]
Hey all, just published https://www.npmjs.com/package/tailwint today. `npx tailwint --fix` runs on the same language server as vscode-tailwindcss intellisense so if you're using the official lsp, this should be able to show you the same output on the cli

**Comment by spassvogel** [comment]
> Hey all, just published https://www.npmjs.com/package/tailwint today. `npx tailwint --fix` runs on the same language server as vscode-tailwindcss intellisense so if you're using the official lsp, this should be able to show you the same output on the cli

That's all well and good but does it work with eslint?

**Comment by peterwangsc** [comment]
> That's all well and good but does it work with eslint?

[tailwint](https://github.com/peterwangsc/tailwint) isn't an ESLint plugin... it's a thin (~50kb) CI linter that works with the official language server independent of eslint or prettier; if you need ESLint-style rules on v4, check out [eslint-plugin-better-tailwindcss](https://github.com/schoero/eslint-plugin-better-tailwindcss). [tailwindlabs](https://github.com/tailwindlabs) officially recommends [prettier-plugin-tailwindcss](https://github.com/tailwindlabs/prettier-plugin-tailwindcss). if you just need a tiny tailwind linter that can run auto-fix from your CLI without a prettier or eslint plugin, then tailwint fills that niche.

**Comment by ronny1020** [comment]
Great to see this is closed! Though v4 support still seems to be in alpha, with known issues like #448 still open.  So should I use this or not?
