### ISSUE TITLE
[BUG] Invalid regular expression

### ISSUE THREAD

**Issue by ocavue** [francoismassart/eslint-plugin-tailwindcss#62]
**Describe the bug**

Awesome project! I found this project very useful for finding some mistake when I writing tailwindcss class names. 

I found an error when I use `eslint-plugin-tailwindcss` with [daisyui](https://github.com/saadeghi/daisyui):

```
Oops! Something went wrong! :(

ESLint: 8.1.0

SyntaxError: Invalid regular expression: /^(drawer-overlay+*)$/: Nothing to repeat
Occurred while linting /[MASKED]/[MASKED].tsx:6
Rule: "tailwindcss/no-custom-classname"
    at new RegExp (<anonymous>)
    at String.<anonymous> (/[MASKED]/node_modules/.pnpm/eslint-plugin-tailwindcss@1.17.0/node_modules/eslint-plugin-tailwindcss/lib/util/groupMethods.js:395:21)
    at Array.findIndex (<anonymous>)
    at Object.getGroupIndex (/[MASKED]/node_modules/.pnpm/eslint-plugin-tailwindcss@1.17.0/node_modules/eslint-plugin-tailwindcss/lib/util/groupMethods.js:392:17)
    at /[MASKED]/node_modules/.pnpm/eslint-plugin-tailwindcss@1.17.0/node_modules/eslint-plugin-tailwindcss/lib/rules/no-custom-classname.js:104:40
    at Array.forEach (<anonymous>)
    at parseForCustomClassNames (/[MASKED]/node_modules/.pnpm/eslint-plugin-tailwindcss@1.17.0/node_modules/eslint-plugin-tailwindcss/lib/rules/no-custom-classname.js:95:18)
    at Object.parseNodeRecursive (/[MASKED]/node_modules/.pnpm/eslint-plugin-tailwindcss@1.17.0/node_modules/eslint-plugin-tailwindcss/lib/util/ast.js:138:5)
    at JSXAttribute (/[MASKED]/node_modules/.pnpm/eslint-plugin-tailwindcss@1.17.0/node_modules/eslint-plugin-tailwindcss/lib/rules/no-custom-classname.js:128:17)
    at ruleErrorHandler (/[MASKED]/node_modules/.pnpm/eslint@8.1.0/node_modules/eslint/lib/linter/linter.js:966:28)
    
```

Daisyui will add some css like the following one:

```
.drawer.drawer-end .drawer-toggle~.drawer-side>.drawer-overlay+* {
  justify-self: end;
  --tw-translate-x: 100%;
}
```

`drawer-overlay+*` seems to be the one that causes this error.

**To Reproduce**

```
$ git clone https://github.com/issueset/eslint-plugin-tailwindcss-issue
$ cd eslint-plugin-tailwindcss-issue
$ pnpm install # you can also use Yarn and NPM 
$ pnpm run build:css
$ pnpm run fix
SyntaxError: Invalid regular expression: /^(drawer-overlay+*)$/: Nothing to repeat
```

**Expected behavior**

No error.

**Screenshots**

N/A

**Environment (please complete the following information):**
 - OS: macOS
 - Softwares + version used: Node.js v16.9.1

**Comment by francoismassart** [comment]
@ocavue thank you for reporting with plenty of details I will take a look at it asap.

**Comment by francoismassart** [comment]
@ocavue https://github.com/issueset/eslint-plugin-tailwindcss-issue => 404

**Comment by ocavue** [comment]
Sorry. I set this repo as private by mistake. It should be public now.

**Comment by francoismassart** [comment]
@ocavue  Please try:

```
npm i eslint-plugin-tailwindcss@beta
```

it should install version `eslint-plugin-tailwindcss@1.17.1-beta.0`

I will release it out of beta after further testing but as I'm on holiday, it will be in few days at least.

Please give me your feedback 😉

**Comment by ocavue** [comment]
I will try it now

**Comment by ocavue** [comment]
It works like charm! Thank you for the quick fix.

**Comment by francoismassart** [comment]
It helps a lot when I get an issue with a demo repo included 😎
